language: python

python:
    - "3.6"

before_install:
  - "python3 setup.py install"

install: pip install -r requirements.txt

script:
  - python3 src/init_trenc.py -f data/DATASET.csv
  - python3 src/init_bordertgraank.py -f data/DATASET.csv